### ISSUE TITLE
box is missing (404)

### ISSUE THREAD

**Issue by lalyos** [implicit-explicit/meetup_hacking#6]
vagrant up fails with this:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
vagrant ssh==> default: Box 'centos70' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'centos70' (v0) for provider: virtualbox
    default: Downloading: http://deltaforce.io/box/centos70-base_1414068169.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

btw, thanks for the valuable insights shared in the recent Docker Meetup Organizers hangout!

**Comment by mrmrcoleman** [comment]
Thanks for reporting this lalyos. I'm looking into thr box issue and I'm glad that you enjoyed the Docker Meetup Organizers meetup.

**Comment by mrmrcoleman** [comment]
Fixed: https://github.com/implicit-explicit/meetup_hacking/commit/ed1ced273a7bb54274988fa77b5b6d3966b6968a
Removed duplicate port forward line: f895cad39f1c70c19b77e55a50b3ad7400af8603

@lalyos Could you test and let me know please?

**Comment by lalyos** [comment]
I confirm it works now. Thanks for the quick fix
